services:
  outline:
    image: outlinewiki/outline:0.82.0
    restart: always
    depends_on:
      - postgres
      - redis
      - dex
    ports:
      - 3001:3000
    environment:
      NODE_ENV: production
      URL: ${URL}
      FORCE_HTTPS: "false"
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      DATABASE_URL: postgres://outline:${POSTGRES_PASSWORD}@postgres:5432/outline
      PGSSLMODE: disable
      REDIS_URL: redis://redis:6379
      FILE_STORAGE: local
      FILE_STORAGE_UPLOAD_MAX_SIZE: 25214400
      OIDC_CLIENT_ID: outline
      OIDC_CLIENT_SECRET: ${CLIENT_SECRET}
      OIDC_AUTH_URI: ${DEX_URL}/auth
      OIDC_TOKEN_URI: ${DEX_URL}/token
      OIDC_USERINFO_URI: ${DEX_URL}/userinfo
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_REPLY_EMAIL: ${SMTP_REPLY_EMAIL}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      SMTP_SECURE: ${SMTP_SECURE}
    volumes:
      - storage-data:/var/lib/outline/data

  dex:
    image: ghcr.io/dexidp/dex:v2.37.0
    restart: always
    volumes:
      - ./config/dex/config.yaml:/etc/dex/config.yaml
    command:
      - dex
      - serve
      - /etc/dex/config.yaml
    ports:
      - 5556:5556
    environment:
      NODE_ENV: production

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: outline
      POSTGRES_USER: outline
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data-outline:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data-outline:/data

volumes:
  postgres_data-outline:
  redis_data-outline:
  storage-data:
